Create version.tf
Created versions.tf file. Ensure that the specific vendor and terraform provider are placed in the same file, else you will encounter the the following error message:

Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/proxmox: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/proxmox